class NuurApp{
constructor(){this.state=this.loadState();this.ibadah=new IbadahModule(this);this.fin=new KeuanganModule(this);this.render()}
defaultState(){return{mode:'ibadah',page:{ibadah:'today',financial:'summary'},worship:{},accounts:DA.map(a=>({...a})),categories:DC.map(c=>({...c})),transactions:[],budgets:{}}}
loadState(){try{const s=localStorage.getItem('myshadow_v2');if(s){const p=JSON.parse(s);return{...this.defaultState(),...p}}}catch(e){}try{const old=localStorage.getItem('myshadow_state');if(old){const p=JSON.parse(old);const ns=this.defaultState();ns.worship=p.worship||{};ns.transactions=p.transactions||[];ns.accounts=p.accounts||DA.map(a=>({...a}));localStorage.removeItem('myshadow_state');return ns}}catch(e){}const s=this.defaultState();seed(s);return s}
save(){try{localStorage.setItem('myshadow_v2',JSON.stringify(this.state))}catch(e){}}
getW(d){return this.state.worship[d]||{sholatWajib:{},sholatSunnah:{},amal:{infaq:0,tadarus:0},puasa:null,dzikir:{pagi:false,petang:false}}}
setW(d,data){this.state.worship[d]=data;this.save()}
switchMode(m){if(m===this.state.mode)return;const o=$('#modeOverlay');o.style.background=m==='ibadah'?'#071510':'#06060E';o.classList.add('active');setTimeout(()=>{this.state.mode=m;document.body.dataset.mode=m;const p=$('#modePill');if(m==='financial')p.classList.add('r');else p.classList.remove('r');$$('.mb-btn').forEach(b=>{b.classList.toggle('on',b.dataset.mode===m)});$('#fab').classList.toggle('show',m==='financial');this.renderNav();this.render()},180);setTimeout(()=>o.classList.remove('active'),450);this.save()}
nav(p){this.state.page[this.state.mode]=p;this.save();this.render()}
render(){const m=this.state.mode,p=this.state.page[m];if(m==='ibadah'){if(p==='today')this.ibadah.renderToday();else if(p==='history')this.ibadah.renderHistory();else this.ibadah.renderInsights()}else{if(p==='summary')this.fin.renderSummary();else if(p==='transactions')this.fin.renderTransactions();else this.fin.renderAnalytics()}$('#dateDisplay').textContent=fmtDate(today());this.renderNav()}
renderNav(){const m=this.state.mode,p=this.state.page[m];let items=[];if(m==='ibadah')items=[{id:'today',i:'fa-sun',l:'Hari Ini'},{id:'history',i:'fa-calendar-days',l:'Riwayat'},{id:'insights',i:'fa-lightbulb',l:'Wawasan'}];else items=[{id:'summary',i:'fa-chart-pie',l:'Ringkasan'},{id:'transactions',i:'fa-receipt',l:'Transaksi'},{id:'analytics',i:'fa-chart-line',l:'Analitik'}];$('#bottomNav').innerHTML=items.map(x=>'<div class="ni '+(p===x.id?'on':'')+'" onclick="app.nav(\''+x.id+'\')"><i class="fa-solid '+x.i+'"></i><span>'+x.l+'</span></div>').join('')}
openModal(h){$('#modalContent').innerHTML=h;$('#modalBackdrop').classList.add('show')}
closeModal(e){if(e&&e.target!==e.currentTarget)return;$('#modalBackdrop').classList.remove('show')}
confirm(msg,cb){const el=document.createElement('div');el.className='cfm';el.id='cfmEl';el.innerHTML='<div class="cfm-box"><div style="font-size:14px;font-weight:600;margin-bottom:4px">'+msg+'</div><div style="font-size:12px;color:var(--txm);margin-bottom:16px">Tindakan ini tidak bisa dibatalkan</div><div class="flex gap-2"><button class="btn btn-g" style="flex:1" onclick="document.getElementById(\'cfmEl\').remove()">Batal</button><button class="btn btn-d" style="flex:1" id="cfmYes">Hapus</button></div></div>';document.body.appendChild(el);setTimeout(()=>el.classList.add('show'),10);$('#cfmYes').onclick=()=>{el.remove();cb()}}

handleAction(el){const a=el.dataset.a;if(!a)return;
switch(a){
case'prayer':{const n=el.dataset.n;const w=this.getW(today());const c=w.sholatWajib[n];const i=STC.indexOf(c);w.sholatWajib[n]=STC[(i+1)%STC.length];this.setW(today(),w);const s=w.sholatWajib[n];if(s==='ontime')toast(SL[n]+' tepat waktu. MasyaAllah.');else if(s==='late')toast(SL[n]+' terlambat.');else if(s==='missed')toast(SL[n]+' tidak dilakukan.');this.render();break}
case'sunnah':{const k=el.dataset.k;const si=SI.find(s=>s.key===k);const w=this.getW(today());const c=w.sholatSunnah[k]||0;const i=si.steps.indexOf(c);w.sholatSunnah[k]=si.steps[(i+1)%si.steps.length];this.setW(today(),w);this.render();break}
case'infaq':{const w=this.getW(today());this.openModal('<h2 class="text-lg font-bold mb-4">Catat Infaq</h2><div class="mb-4"><label style="font-size:11px;color:var(--tx2);display:block;margin-bottom:5px">Jumlah (Rp)</label><input class="inp inp-lg" type="number" id="infA" placeholder="0" inputmode="numeric" value="'+(w.amal.infaq||'')+'"></div><div class="flex flex-wrap gap-2 mb-4">'+[1e4,25e3,5e4,1e5].map(v=>'<div class="ch" onclick="document.getElementById(\'infA\').value='+v+'">'+fmtRp(v)+'</div>').join('')+'</div><button class="btn btn-p" style="width:100%" onclick="app.subInfaq()">Simpan</button>');break}
case'tadarus':{const w=this.getW(today());this.openModal('<h2 class="text-lg font-bold mb-4">Tadarus Al-Quran</h2><div class="mb-4"><label style="font-size:11px;color:var(--tx2);display:block;margin-bottom:5px">Jumlah Juz</label><input class="inp inp-lg" type="number" id="tadA" placeholder="0" inputmode="numeric" min="0" max="30" value="'+(w.amal.tadarus||'')+'"></div><div class="flex flex-wrap gap-2 mb-4">'+[1,2,3,5].map(v=>'<div class="ch" onclick="document.getElementById(\'tadA\').value='+v+'">'+v+' juz</div>').join('')+'</div><button class="btn btn-p" style="width:100%" onclick="app.subTad()">Simpan</button>');break}
case'puasa':{const w=this.getW(today());if(w.puasa){w.puasa=null;this.setW(today(),w);toast('Puasa dibatalkan');this.render()}else{this.openModal('<h2 class="text-lg font-bold mb-4">Catat Puasa Sunnah</h2><div class="flex flex-col gap-2 mb-4">'+PUASA.map(p=>'<div class="ch" onclick="app.subPuasa(\''+p.key+'\')"><i class="fa-solid fa-moon" style="font-size:11px"></i> '+p.label+'</div>').join('')+'</div><button class="btn btn-g" style="width:100%" onclick="app.closeModal({target:document.getElementById(\'modalBackdrop\')})">Batal</button>')}break}
case'dzikir':{const t=el.dataset.t;const w=this.getW(today());w.dzikir[t]=!w.dzikir[t];this.setW(today(),w);toast(w.dzikir[t]?(t==='pagi'?'Dzikir pagi dicatat':'Dzikir petang dicatat'):(t==='pagi'?'Dzikir pagi dibatalkan':'Dzikir petang dibatalkan'));this.render();break}
case'dayDetail':this.ibadah.openDayDetail(el.dataset.d);break;
case'addAccount':this.openModal('<h2 class="text-lg font-bold mb-4">Tambah Akun</h2><div class="mb-3"><label style="font-size:11px;color:var(--tx2);display:block;margin-bottom:5px">Nama</label><input class="inp" type="text" id="acN" placeholder="OVO"></div><div class="mb-3"><label style="font-size:11px;color:var(--tx2);display:block;margin-bottom:5px">Tipe</label><div class="flex gap-2" id="acTC"><div class="ch on" data-at="cash" onclick="$$(\'#acTC .ch\').forEach(c=>c.classList.toggle(\'on\',c.dataset.at===\'cash\'));app._at=\'cash\'">Tunai</div><div class="ch" data-at="bank" onclick="$$(\'#acTC .ch\').forEach(c=>c.classList.toggle(\'on\',c.dataset.at===\'bank\'));app._at=\'bank\'">Bank</div><div class="ch" data-at="ewallet" onclick="$$(\'#acTC .ch\').forEach(c=>c.classList.toggle(\'on\',c.dataset.at===\'ewallet\'));app._at=\'ewallet\'">E-Wallet</div></div></div><div class="mb-4"><label style="font-size:11px;color:var(--tx2);display:block;margin-bottom:5px">Saldo Awal</label><input class="inp" type="number" id="acB" placeholder="0" inputmode="numeric"></div><button class="btn btn-p" style="width:100%" onclick="app.subAcc()">Simpan</button>');this._at='cash';break;
case'delTx':{const id=el.dataset.id;const tx=this.state.transactions.find(t=>t.id===id);if(tx)this.confirm('Hapus "'+tx.description+'"?',()=>{const ac=this.state.accounts.find(a=>a.id===tx.accountId);if(ac){if(tx.type==='income')ac.balance-=tx.amount;else if(tx.type==='expense')ac.balance+=tx.amount;if(tx.type==='transfer'){const to=this.state.accounts.find(a=>a.id===tx.toAccountId);if(to)to.balance-=tx.amount;ac.balance+=tx.amount}}this.state.transactions=this.state.transactions.filter(t=>t.id!==id);this.save();toast('Transaksi dihapus');this.render()});break}
}}

subInfaq(){const a=parseInt($('#infA').value)||0;const w=this.getW(today());w.amal.infaq=a;this.setW(today(),w);$('#modalBackdrop').classList.remove('show');toast(a>0?'Infaq dicatat. Jazakallahu khairan':'Infaq direset');this.render()}
subTad(){const a=Math.min(30,Math.max(0,parseInt($('#tadA').value)||0));const w=this.getW(today());w.amal.tadarus=a;this.setW(today(),w);$('#modalBackdrop').classList.remove('show');toast(a>0?a+' juz dicatat. Barakallahu fik':'Tadarus direset');this.render()}
subPuasa(k){const w=this.getW(today());w.puasa=k;this.setW(today(),w);$('#modalBackdrop').classList.remove('show');toast('Puasa '+PUASA.find(p=>p.key===k).label+' dicatat');this.render()}
subAcc(){const n=$('#acN').value.trim(),b=parseInt($('#acB').value)||0;if(!n){toast('Masukkan nama');return}const ic={cash:'fa-wallet',bank:'fa-building-columns',ewallet:'fa-mobile-screen'};const co=['#F59E0B','#22D3EE','#A78BFA','#FB923C','#EC4899','#22C55E'];this.state.accounts.push({id:uid(),name:n,type:this._at,balance:b,color:co[this.state.accounts.length%co.length],icon:ic[this._at]});this.save();$('#modalBackdrop').classList.remove('show');toast('Akun ditambahkan');this.render()}
}

const app=new NuurApp();
document.getElementById('mainContent').addEventListener('click',e=>{const t=e.target.closest('[data-a]');if(t)app.handleAction(t)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.getElementById('modalBackdrop').classList.remove('show');const c=document.getElementById('cfmEl');if(c)c.remove()}});
